export type TIconName =
  | "email"
  | "phone"
  | "compare"
  | "arrowCircleLeft"
  | "arrowCircleRight"
  | "office"
  | "calendar"
  | "fabric"
  | "facebook"
  | "instagram"
  | "ribbonStarFilled"
  | "location"
  | "person"
  | "flag"
  | "ruler"
  | "deliveryTruck";
